name: CI/CD Pipeline

on:
  push:
    branches:
      - nothing

jobs:
  docker-build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: eliasabichakra
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: |
        IMAGE_TAG="${{ secrets.DOCKER_IMAGE }}:${{ github.run_number }}"
        docker build -t $IMAGE_TAG .
        echo "Built image with tag $IMAGE_TAG"

    - name: Push Docker image to DockerHub
      run: |
        IMAGE_TAG="${{ secrets.DOCKER_IMAGE }}:${{ github.run_number }}"
        docker push $IMAGE_TAG
        echo "Pushed image $IMAGE_TAG to DockerHub"

    - name: SSH to Server and Run Script
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.IP_MAIN }}
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Run the remover script
          ./remover.sh

          # Pull the latest image from DockerHub
          docker pull ${{ env.DOCKER_IMAGE }}:${{ github.run_number }}

          # Run the Docker container
          docker run -d --name series-backend-container -v /home/ubuntu/.env:/app/.env -p 3000:3000 ${{ secrets.DOCKER_IMAGE }}:${{ github.run_number }}